preserve existing raw files in case of download failures

diff --git a/osint-tool b/osint-tool
--- a/osint-tool
+++ b/osint-tool
@@ -26,33 +26,46 @@ TMPFEED="${TEMPDIR}/tmpfeed.csv"
 IPFEED="${TEMPDIR}/ipfeed.csv"
 ATFEED="${TEMPDIR}/atfeed.csv"
 
+# set feed timestamp value
+TIMESTAMP=$(date '+%d/%m/%Y %H:%M:%S')
+
 # ensure ipallow.list is sorted
 sort "${ALLOWLIST}" > "${TEMPDIR}/allowlist.sorted"
 cp "${TEMPDIR}/allowlist.sorted" "${ALLOWLIST}"
 
-do_download(){
-  # nuke TEMPDIR and recreate it
-  [ -d "${TEMPDIR}" ] && rm -rf "${TEMPDIR}"
-  mkdir -p "${TEMPDIR}"
+# ensure TEMPDIR exists
+mkdir -p "${TEMPDIR}"
 
+do_download(){
   # iterate through the available .feed files
-  find "${FEEDDIR}" -type f -print0 | while IFS= read -r -d $'\0' FEEDFILE;
+  find "${FEEDDIR}" -type f -name *.feed -print0 | while IFS= read -r -d $'\0' FEEDFILE;
   #find "${FEEDDIR}" -name malwareworld-suspiciousips.feed -print0 | while IFS= read -r -d $'\0' FEEDFILE;
   do
     . "${FEEDFILE}" ;
     [ -z "${FEEDNAME}" ] && echo "error: missing FEEDNAME in ${FEEDFILE}" && exit 1
     [ -z "${FEEDURL}" ] && echo "error: missing FEEDURL in ${FEEDFILE}" && exit 1
+    OLDFILE="${TEMPDIR}/$(basename ${FEEDFILE%.*}).old"
     RAWFILE="${TEMPDIR}/$(basename ${FEEDFILE%.*}).raw"
     RAWTEMP="${TEMPDIR}/$(basename ${FEEDFILE%.*}).tmp"
     RAWSORT="${TEMPDIR}/$(basename ${FEEDFILE%.*}).sort"
     RAWAT="${TEMPDIR}/$(basename ${FEEDFILE%.*}).attr"
     RAWIP="${TEMPDIR}/$(basename ${FEEDFILE%.*}).ip"
 
+    # preserve old file until we successfully download a replacement
+    mv "${RAWFILE}" "${OLDFILE}"
+
     # download the feed
     wget "${FEEDURL}" -O "${RAWFILE}" --no-check-certificate --quiet --timeout=10
 
-    # post-processing if the feed configures it
-    #[ -n "${FEEDHANDLING}" ] && "${FEEDHANDLING}"
+    # check wget return code is zero (success)
+    if [ $? -ne 0 ]; then
+      # restore the previous feed file
+      mv "${OLDFILE}" "${RAWFILE}"
+    else
+      # insert timestamp to new file
+      sed -i "1 i\Raw Feed File Created: ${TIMESTAMP}" "${RAWFILE}"
+      rm -f "${OLDFILE}"
+    fi
 
     # remove blank lines
     sed -i '/^$/d' "${RAWFILE}"
@@ -113,11 +126,6 @@ do_download(){
       echo "${IP},MailOriginIP,mime,ipblocklist" >> "${ATFEED}"
     done
   fi
-
-  # insert timestamp to files
-  #TIMESTAMP=$(date '+%d/%m/%Y %H:%M:%S')
-  #sed -i "1 i\Feed created: ${TIMESTAMP}" "${ATFEED}"
-  #sed -i "1 i\Feed created: ${TIMESTAMP}" "${IPFEED}"
 
   # copy feed files to webserver/publish folder
   cp -fp "${ATFEED}" "${OSINTAT}"
